/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef SocialServices_CONSTANTS_H
#define SocialServices_CONSTANTS_H

#include "SocialServices_types.h"



class SocialServicesConstants {
 public:
  SocialServicesConstants();

};

extern const SocialServicesConstants g_SocialServices_constants;



#endif
