/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "SocialServices_constants.h"



const SocialServicesConstants g_SocialServices_constants;

SocialServicesConstants::SocialServicesConstants() {
}



