/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef token_CONSTANTS_H
#define token_CONSTANTS_H

#include "token_types.h"



class tokenConstants {
 public:
  tokenConstants();

};

extern const tokenConstants g_token_constants;



#endif
