/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "token_types.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>




token::~token() throw() {
}


void token::__set_zuid(const int32_t val) {
  this->zuid = val;
}

uint32_t token::read(::apache::thrift::protocol::TProtocol* iprot) {

  apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->zuid);
          this->__isset.zuid = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t token::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("token");

  xfer += oprot->writeFieldBegin("zuid", ::apache::thrift::protocol::T_I32, 1);
  xfer += oprot->writeI32(this->zuid);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(token &a, token &b) {
  using ::std::swap;
  swap(a.zuid, b.zuid);
  swap(a.__isset, b.__isset);
}

token::token(const token& other0) {
  zuid = other0.zuid;
  __isset = other0.__isset;
}
token& token::operator=(const token& other1) {
  zuid = other1.zuid;
  __isset = other1.__isset;
  return *this;
}
void token::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "token(";
  out << "zuid=" << to_string(zuid);
  out << ")";
}


